name: 기능 개발
description: 기능 개발에 대한 이슈를 작성해주세요.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        기능 개발을 위한 이슈를 작성해주셔서 감사합니다! 아래 양식을 작성해주세요.
  - type: textarea
    id: feature-description
    attributes:
      label: 개발하고자 하는 기능 설명
      description: 어떤 기능을 개발하고 싶은지 자세히 설명해주세요.
      placeholder: 예: 사용자가 자신의 챔피언 통계를 볼 수 있는 대시보드 기능을 개발하고 싶습니다.
    validations:
      required: true
  - type: textarea
    id: implementation-idea
    attributes:
      label: 구현 아이디어
      description: 기능 구현에 대한 구체적인 아이디어가 있다면 공유해주세요.
      placeholder: 구현 방법에 대한 아이디어나 참고할 만한 예시를 설명해주세요.
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 이 기능의 우선순위를 선택해주세요.
      options:
        - 높음
        - 중간
        - 낮음
    validations:
      required: true
  - type: dropdown
    id: estimated-effort
    attributes:
      label: 예상 소요 시간
      description: 이 기능 개발에 예상되는 소요 시간을 선택해주세요.
      options:
        - 1일 이내
        - 1주일 이내
        - 2주일 이내
        - 1개월 이내
        - 1개월 이상
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: 추가 정보
      description: 기능 개발과 관련된 추가 정보나 참고자료를 공유해주세요.
      placeholder: 스크린샷, 참고할 만한 사이트, 추가 설명 등을 작성해주세요.
