name: 기능 개발
description: 새로운 기능 개발에 대한 이슈를 작성해주세요.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        새로운 기능을 제안해주셔서 감사합니다! 아래 항목들을 작성해주세요.
  - type: input
    id: feature-name
    attributes:
      label: 기능 이름
      placeholder: 예) 사용자 알림 시스템 추가
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: 기능 설명
      description: 어떤 기능인지, 왜 필요한지를 설명해주세요.
      placeholder: 이 기능은 사용자에게 새로운 알림을 제공하며, UX 개선에 기여합니다.
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: 세부 요구사항
      description: 해당 기능에 필요한 조건이나 동작을 명시해주세요.
      placeholder: 예) - 특정 조건일 때 알림 생성 / - 사용자는 알림을 읽음으로 표시할 수 있어야 함
  - type: checkboxes
    id: impact
    attributes:
      label: 관련된 영역
      description: 이 기능이 영향을 주는 부분이 있다면 선택해주세요.
      options:
        - label: 프론트엔드
        - label: 백엔드
        - label: API
        - label: DB
        - label: 테스트 코드
  - type: textarea
    id: additional-info
    attributes:
      label: 기타 참고 사항
      placeholder: 관련 문서, 레퍼런스 링크 등을 여기에 입력해주세요.
